print("johny Johny")
print("Yes papa")
print("Eating Sugar?")
#print("Yes papa!")
print("No papa!")
print("Telling lies?")
#print("Yes Papa!")
print("No papa!")
print("Open your mouth")
print("Ah, ah, ah!")